  Listas Dobles Test.cpp
     Creando biblioteca C:\Users\LENOVO\Documents\GitHub\Team8-DataStructure-NRC3294\l-PARCIAL\Taller 11 Listas Dobles Enlazadas\Debug\Listas Dobles Test.lib y objeto C:\Users\LENOVO\Documents\GitHub\Team8-DataStructure-NRC3294\l-PARCIAL\Taller 11 Listas Dobles Enlazadas\Debug\Listas Dobles Test.exp
Listas Dobles Test.obj : error LNK2019: símbolo externo "public: __thiscall Nodo::Nodo(int)" (??0Nodo@@QAE@H@Z) sin resolver al que se hace referencia en la función "public: void __thiscall ListaDobleEnlazada::insertarCabeza(int)" (?insertarCabeza@ListaDobleEnlazada@@QAEXH@Z)
Listas Dobles Test.obj : error LNK2019: símbolo externo "public: class Nodo * __thiscall Nodo::getSiguiente(void)" (?getSiguiente@Nodo@@QAEPAV1@XZ) sin resolver al que se hace referencia en la función "public: void __thiscall ListasDoblesTest::ListasDoblesTest::insertarCabezaTest(void)" (?insertarCabezaTest@ListasDoblesTest@1@QAEXXZ)
Listas Dobles Test.obj : error LNK2019: símbolo externo "public: void __thiscall Nodo::setSiguiente(class Nodo *)" (?setSiguiente@Nodo@@QAEXPAV1@@Z) sin resolver al que se hace referencia en la función "public: void __thiscall ListaDobleEnlazada::insertarCabeza(int)" (?insertarCabeza@ListaDobleEnlazada@@QAEXH@Z)
Listas Dobles Test.obj : error LNK2019: símbolo externo "public: void __thiscall Nodo::setAnterior(class Nodo *)" (?setAnterior@Nodo@@QAEXPAV1@@Z) sin resolver al que se hace referencia en la función "public: void __thiscall ListaDobleEnlazada::insertarCabeza(int)" (?insertarCabeza@ListaDobleEnlazada@@QAEXH@Z)
Listas Dobles Test.obj : error LNK2019: símbolo externo "public: int __thiscall Nodo::getValor(void)" (?getValor@Nodo@@QAEHXZ) sin resolver al que se hace referencia en la función "public: void __thiscall ListaDobleEnlazada::recorrer(class std::function<void __cdecl(int,int)>)" (?recorrer@ListaDobleEnlazada@@QAEXV?$function@$$A6AXHH@Z@std@@@Z)
C:\Users\LENOVO\Documents\GitHub\Team8-DataStructure-NRC3294\l-PARCIAL\Taller 11 Listas Dobles Enlazadas\Debug\Listas Dobles Test.dll : fatal error LNK1120: 5 externos sin resolver
